### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by CombineSlayer24** [gillian-guide/GTAIV.EFLC.FusionFix-GFWL#2]
### What should happen

Would the latest changes that got added to the main repository get added here for the GFWL fork version? It's been getting some massive updates recently.

### Checklist

- [ ] Check the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already implemented.
- [ ] [Search for other requests](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same feature.

**Comment by SandeMC** [comment]
Done

**Comment by CombineSlayer24** [comment]
> Done

Awesome. You the goat for GWFL-*less, heh* users.
