### ISSUE TITLE
Static blip animations

### ISSUE THREAD

**Issue by sh30g0r4d** [gillian-guide/GTAIV.EFLC.FusionFix-GFWL#3]
### Game version this happens in

v1.2.0.59

### What area of the game

Blip UI animations doesn't work and stay static since 3.2.0 on preCE/GFWL versions (police vehicles on radar etc)

### What should happen

Blip animations should work

### Last working version

v3.1.1

### Checklist

- [X] Test in the [latest git build](https://ci.appveyor.com/api/projects/ThirteenAG/gtaiv-eflc-fusionfix/artifacts/GTAIV.EFLC.FusionFix.zip) in case it's already fixed.
- [X] [Search for other reports](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/search?q=my+issue&type=issues) of the same issue.
- [X] Include logs or screenshots of issue.

**Comment by SandeMC** [comment]
fixed
